### ISSUE TITLE
Question about the project name

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-rs#46]
Just curious, the project was named with an underscore instead of a hyphen. It might be more common to use a hyphen, [setuptools-scm renamed recently](https://github.com/pypa/setuptools-scm/pull/1068). Maybe this isn't the case for the Rust project.

**Comment by 2bndy5** [comment]
I agree. I was afraid to mess up things. There are some external integrations that would need to be updated as well 
- [ ] ReadTheDocs
- [ ] PyPI
- [ ] testPyPI
- [ ] crates-io
- [ ] npm
- [ ] any other links to the project.

I have to look into this more. I'm not sure if it's possible after publishing some pre-releases.

**Comment by 2bndy5** [comment]
The repo name uses underscores, but all packages published use hyphens. Did you want to rename the repo?

**Comment by 2bndy5** [comment]
I'm worried it might mess up package indexes (npmjs, pypi, crates-io). I'll try it out after I get #47 merged. I plan on another pre-release candidate. It may be more work than it is worth though.

**Comment by 2bndy5** [comment]
done. I had nothing to worry about.
